declare const styles: {
    questionComponent: string;
    LinkButton: string;
    error: string;
    fileUpload: string;
    container: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    description: string;
    'ms-Dialog-button': string;
    'ms-Dialog-button--close': string;
    button_e07b5233: string;
    'ms-Button': string;
    'ms-Button--icon': string;
    'css-161': string;
    button: string;
    label: string;
};
export default styles;
